#!/bin/bash

#configuration by user
ve_target_id=0
ve_conf_path="/etc/vz/conf/"
ve_data_path="/data/vz/private/"
vzctl_create_params="--ostemplate ubuntu-10.04-minimal_10.04_amd64 --config web --ipadd <ip> --hostname <hostname>"
ve_root_pw="<password>"

#script
if [ -a "$ve_conf_path$ve_target_id.conf" ]
then
    #assume that the VE exists, check if we should reset it?
    if [ -a "$ve_data_path$ve_target_id/etc/reset-ve" ] 
    then
        #the user wants the VE resetted
   	vzctl exec $ve_target_id "rm /etc/reset-ve"
        vzctl stop $ve_target_id
        vzctl destroy $ve_target_id
        vzctl create $ve_target_id $vzctl_create_params
        vzctl start $ve_target_id
        vzctl exec $ve_target_id "echo "root:$ve_root_pw" | chpasswd"

    fi 
    #if the file does not exist, do nothing
else
    #the VE config does not exist, create the VE for the first time and start it.
    vzctl create $ve_target_id $vzctl_create_params
    vzctl start $ve_target_id
    vzctl exec $ve_target_id "echo "root:$ve_root_pw" | chpasswd"
fi
